[2024-12-18T10:00:01.718+0000] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2024-12-18T10:00:01.736+0000] {taskinstance.py:2613} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: etl_mongodb.etl_mongo_to_clickhouse scheduled__2024-12-18T09:00:00+00:00 [queued]>
[2024-12-18T10:00:01.744+0000] {taskinstance.py:2613} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: etl_mongodb.etl_mongo_to_clickhouse scheduled__2024-12-18T09:00:00+00:00 [queued]>
[2024-12-18T10:00:01.744+0000] {taskinstance.py:2866} INFO - Starting attempt 1 of 2
[2024-12-18T10:00:01.758+0000] {taskinstance.py:2889} INFO - Executing <Task(PythonOperator): etl_mongo_to_clickhouse> on 2024-12-18 09:00:00+00:00
[2024-12-18T10:00:01.767+0000] {warnings.py:112} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:70: DeprecationWarning: This process (pid=284) is multi-threaded, use of fork() may lead to deadlocks in the child.
  pid = os.fork()

[2024-12-18T10:00:01.769+0000] {standard_task_runner.py:72} INFO - Started process 286 to run task
[2024-12-18T10:00:01.770+0000] {standard_task_runner.py:104} INFO - Running: ['***', 'tasks', 'run', 'etl_mongodb', 'etl_mongo_to_clickhouse', 'scheduled__2024-12-18T09:00:00+00:00', '--job-id', '63', '--raw', '--subdir', 'DAGS_FOLDER/dag.py', '--cfg-path', '/tmp/tmpxeglbd40']
[2024-12-18T10:00:01.772+0000] {standard_task_runner.py:105} INFO - Job 63: Subtask etl_mongo_to_clickhouse
[2024-12-18T10:00:01.828+0000] {task_command.py:467} INFO - Running <TaskInstance: etl_mongodb.etl_mongo_to_clickhouse scheduled__2024-12-18T09:00:00+00:00 [running]> on host ea437989725c
[2024-12-18T10:00:02.141+0000] {taskinstance.py:3132} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='Tohid' AIRFLOW_CTX_DAG_ID='etl_mongodb' AIRFLOW_CTX_TASK_ID='etl_mongo_to_clickhouse' AIRFLOW_CTX_EXECUTION_DATE='2024-12-18T09:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2024-12-18T09:00:00+00:00'
[2024-12-18T10:00:02.142+0000] {logging_mixin.py:190} INFO - Task instance is in running state
[2024-12-18T10:00:02.142+0000] {logging_mixin.py:190} INFO -  Previous state of the Task instance: queued
[2024-12-18T10:00:02.142+0000] {logging_mixin.py:190} INFO - Current task name:etl_mongo_to_clickhouse state:running start_date:2024-12-18 10:00:01.736573+00:00
[2024-12-18T10:00:02.142+0000] {logging_mixin.py:190} INFO - Dag name:etl_mongodb and current dag run status:running
[2024-12-18T10:00:02.143+0000] {taskinstance.py:731} INFO - ::endgroup::
[2024-12-18T10:00:02.179+0000] {logging_mixin.py:190} INFO - Number of documents in 'students' collection: 10000
[2024-12-18T10:00:02.202+0000] {taskinstance.py:3311} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 767, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 733, in _execute_callable
    return ExecutionCallableRunner(
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 422, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 238, in execute
    return_value = self.execute_callable()
                   ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 256, in execute_callable
    return runner.run(*self.op_args, **self.op_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/airflow/dags/process.py", line 32, in etl
    distinct_ids = client_clickhouse.query("SELECT DISTINCT(id) FROM airflow.students")
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/clickhouse_connect/driver/client.py", line 222, in query
    return self._query_with_context(query_context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/clickhouse_connect/driver/httpclient.py", line 229, in _query_with_context
    response = self._raw_request(body,
               ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/clickhouse_connect/driver/httpclient.py", line 462, in _raw_request
    self._error_handler(response)
  File "/home/airflow/.local/lib/python3.12/site-packages/clickhouse_connect/driver/httpclient.py", line 385, in _error_handler
    raise OperationalError(err_str) if retried else DatabaseError(err_str) from None
clickhouse_connect.driver.exceptions.DatabaseError: HTTPDriver for http://clickhouse-etl:8123 received ClickHouse error code 60
 Code: 60. DB::Exception: Unknown table expression identifier '***.students' in scope SELECT DISTINCT id FROM ***.students. (UNKNOWN_TABLE) (version 24.11.1.2557 (official build))

[2024-12-18T10:00:02.218+0000] {logging_mixin.py:190} INFO - Task instance in failure state
[2024-12-18T10:00:02.218+0000] {logging_mixin.py:190} INFO - Task start:2024-12-18 10:00:01.736573+00:00 end:2024-12-18 10:00:02.218002+00:00 duration:0.481429
[2024-12-18T10:00:02.219+0000] {logging_mixin.py:190} INFO - Task:<Task(PythonOperator): etl_mongo_to_clickhouse> dag:<DAG: etl_mongodb> dagrun:<DagRun etl_mongodb @ 2024-12-18 09:00:00+00:00: scheduled__2024-12-18T09:00:00+00:00, state:running, queued_at: 2024-12-18 10:00:00.123898+00:00. externally triggered: False>
[2024-12-18T10:00:02.219+0000] {logging_mixin.py:190} INFO - Failure caused by HTTPDriver for http://clickhouse-etl:8123 received ClickHouse error code 60
 Code: 60. DB::Exception: Unknown table expression identifier '***.students' in scope SELECT DISTINCT id FROM ***.students. (UNKNOWN_TABLE) (version 24.11.1.2557 (official build))
[2024-12-18T10:00:02.219+0000] {taskinstance.py:1225} INFO - Marking task as UP_FOR_RETRY. dag_id=etl_mongodb, task_id=etl_mongo_to_clickhouse, run_id=scheduled__2024-12-18T09:00:00+00:00, execution_date=20241218T090000, start_date=20241218T100001, end_date=20241218T100002
[2024-12-18T10:00:02.241+0000] {taskinstance.py:340} INFO - ::group::Post task execution logs
[2024-12-18T10:00:02.242+0000] {standard_task_runner.py:124} ERROR - Failed to execute job 63 for task etl_mongo_to_clickhouse (HTTPDriver for http://clickhouse-etl:8123 received ClickHouse error code 60
 Code: 60. DB::Exception: Unknown table expression identifier '***.students' in scope SELECT DISTINCT id FROM ***.students. (UNKNOWN_TABLE) (version 24.11.1.2557 (official build))
; 286)
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/task/task_runner/standard_task_runner.py", line 117, in _start_by_fork
    ret = args.func(args, dag=self.dag)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/cli/cli_config.py", line 49, in command
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/cli.py", line 116, in wrapper
    return f(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/cli/commands/task_command.py", line 483, in task_run
    task_return_code = _run_task_by_selected_method(args, _dag, ti)
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/cli/commands/task_command.py", line 256, in _run_task_by_selected_method
    return _run_raw_task(args, ti)
           ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/cli/commands/task_command.py", line 341, in _run_raw_task
    return ti._run_raw_task(
           ^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/session.py", line 97, in wrapper
    return func(*args, session=session, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 3005, in _run_raw_task
    return _run_raw_task(
           ^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 273, in _run_raw_task
    TaskInstance._execute_task_with_callbacks(
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 3159, in _execute_task_with_callbacks
    result = self._execute_task(context, task_orig)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 3183, in _execute_task
    return _execute_task(self, context, task_orig)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 767, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 733, in _execute_callable
    return ExecutionCallableRunner(
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 422, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 238, in execute
    return_value = self.execute_callable()
                   ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 256, in execute_callable
    return runner.run(*self.op_args, **self.op_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/airflow/dags/process.py", line 32, in etl
    distinct_ids = client_clickhouse.query("SELECT DISTINCT(id) FROM airflow.students")
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/clickhouse_connect/driver/client.py", line 222, in query
    return self._query_with_context(query_context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/clickhouse_connect/driver/httpclient.py", line 229, in _query_with_context
    response = self._raw_request(body,
               ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/clickhouse_connect/driver/httpclient.py", line 462, in _raw_request
    self._error_handler(response)
  File "/home/airflow/.local/lib/python3.12/site-packages/clickhouse_connect/driver/httpclient.py", line 385, in _error_handler
    raise OperationalError(err_str) if retried else DatabaseError(err_str) from None
clickhouse_connect.driver.exceptions.DatabaseError: HTTPDriver for http://clickhouse-etl:8123 received ClickHouse error code 60
 Code: 60. DB::Exception: Unknown table expression identifier '***.students' in scope SELECT DISTINCT id FROM ***.students. (UNKNOWN_TABLE) (version 24.11.1.2557 (official build))

[2024-12-18T10:00:02.304+0000] {local_task_job_runner.py:266} INFO - Task exited with return code 1
[2024-12-18T10:00:02.349+0000] {taskinstance.py:3895} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-12-18T10:00:02.351+0000] {local_task_job_runner.py:245} INFO - ::endgroup::
[2024-12-18T10:16:12.435+0000] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2024-12-18T10:16:12.490+0000] {taskinstance.py:2613} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: etl_mongodb.etl_mongo_to_clickhouse scheduled__2024-12-18T09:00:00+00:00 [queued]>
[2024-12-18T10:16:12.512+0000] {taskinstance.py:2613} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: etl_mongodb.etl_mongo_to_clickhouse scheduled__2024-12-18T09:00:00+00:00 [queued]>
[2024-12-18T10:16:12.513+0000] {taskinstance.py:2866} INFO - Starting attempt 1 of 2
[2024-12-18T10:16:12.542+0000] {taskinstance.py:2889} INFO - Executing <Task(PythonOperator): etl_mongo_to_clickhouse> on 2024-12-18 09:00:00+00:00
[2024-12-18T10:16:12.559+0000] {warnings.py:112} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:70: DeprecationWarning: This process (pid=96) is multi-threaded, use of fork() may lead to deadlocks in the child.
  pid = os.fork()

[2024-12-18T10:16:12.561+0000] {standard_task_runner.py:72} INFO - Started process 106 to run task
[2024-12-18T10:16:12.570+0000] {standard_task_runner.py:104} INFO - Running: ['***', 'tasks', 'run', 'etl_mongodb', 'etl_mongo_to_clickhouse', 'scheduled__2024-12-18T09:00:00+00:00', '--job-id', '75', '--raw', '--subdir', 'DAGS_FOLDER/dag.py', '--cfg-path', '/tmp/tmpekvc2f0g']
[2024-12-18T10:16:12.575+0000] {standard_task_runner.py:105} INFO - Job 75: Subtask etl_mongo_to_clickhouse
[2024-12-18T10:16:12.748+0000] {task_command.py:467} INFO - Running <TaskInstance: etl_mongodb.etl_mongo_to_clickhouse scheduled__2024-12-18T09:00:00+00:00 [running]> on host ef884cc6896f
[2024-12-18T10:16:13.607+0000] {taskinstance.py:3132} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='Tohid' AIRFLOW_CTX_DAG_ID='etl_mongodb' AIRFLOW_CTX_TASK_ID='etl_mongo_to_clickhouse' AIRFLOW_CTX_EXECUTION_DATE='2024-12-18T09:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2024-12-18T09:00:00+00:00'
[2024-12-18T10:16:13.608+0000] {logging_mixin.py:190} INFO - Task instance is in running state
[2024-12-18T10:16:13.608+0000] {logging_mixin.py:190} INFO -  Previous state of the Task instance: queued
[2024-12-18T10:16:13.609+0000] {logging_mixin.py:190} INFO - Current task name:etl_mongo_to_clickhouse state:running start_date:2024-12-18 10:16:12.491182+00:00
[2024-12-18T10:16:13.609+0000] {logging_mixin.py:190} INFO - Dag name:etl_mongodb and current dag run status:running
[2024-12-18T10:16:13.609+0000] {taskinstance.py:731} INFO - ::endgroup::
[2024-12-18T10:16:13.767+0000] {logging_mixin.py:190} INFO - Number of documents in 'students' collection: 10000
[2024-12-18T10:16:13.884+0000] {logging_mixin.py:190} INFO - Inserted 10 records into ClickHouse.
[2024-12-18T10:16:13.886+0000] {python.py:240} INFO - Done. Returned value was: None
[2024-12-18T10:16:13.909+0000] {taskinstance.py:340} INFO - ::group::Post task execution logs
[2024-12-18T10:16:13.909+0000] {taskinstance.py:352} INFO - Marking task as SUCCESS. dag_id=etl_mongodb, task_id=etl_mongo_to_clickhouse, run_id=scheduled__2024-12-18T09:00:00+00:00, execution_date=20241218T090000, start_date=20241218T101612, end_date=20241218T101613
[2024-12-18T10:16:13.930+0000] {logging_mixin.py:190} INFO - Task instance in success state
[2024-12-18T10:16:13.931+0000] {logging_mixin.py:190} INFO -  Previous state of the Task instance: running
[2024-12-18T10:16:13.931+0000] {logging_mixin.py:190} INFO - Dag name:etl_mongodb queued_at:2024-12-18 10:16:06.630999+00:00
[2024-12-18T10:16:13.932+0000] {logging_mixin.py:190} INFO - Task hostname:ef884cc6896f operator:PythonOperator
[2024-12-18T10:16:13.979+0000] {local_task_job_runner.py:266} INFO - Task exited with return code 0
[2024-12-18T10:16:14.019+0000] {taskinstance.py:3895} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-12-18T10:16:14.021+0000] {local_task_job_runner.py:245} INFO - ::endgroup::
