[2024-12-18T09:55:30.585+0000] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2024-12-18T09:55:30.656+0000] {taskinstance.py:2613} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: etl_mongodb.etl_mongo_to_clickhouse scheduled__2024-12-18T01:00:00+00:00 [queued]>
[2024-12-18T09:55:30.679+0000] {taskinstance.py:2613} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: etl_mongodb.etl_mongo_to_clickhouse scheduled__2024-12-18T01:00:00+00:00 [queued]>
[2024-12-18T09:55:30.680+0000] {taskinstance.py:2866} INFO - Starting attempt 1 of 2
[2024-12-18T09:55:30.735+0000] {taskinstance.py:2889} INFO - Executing <Task(PythonOperator): etl_mongo_to_clickhouse> on 2024-12-18 01:00:00+00:00
[2024-12-18T09:55:30.773+0000] {warnings.py:112} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:70: DeprecationWarning: This process (pid=92) is multi-threaded, use of fork() may lead to deadlocks in the child.
  pid = os.fork()

[2024-12-18T09:55:30.775+0000] {standard_task_runner.py:72} INFO - Started process 110 to run task
[2024-12-18T09:55:30.777+0000] {standard_task_runner.py:104} INFO - Running: ['***', 'tasks', 'run', 'etl_mongodb', 'etl_mongo_to_clickhouse', 'scheduled__2024-12-18T01:00:00+00:00', '--job-id', '47', '--raw', '--subdir', 'DAGS_FOLDER/dag.py', '--cfg-path', '/tmp/tmpdyjuza5w']
[2024-12-18T09:55:30.779+0000] {standard_task_runner.py:105} INFO - Job 47: Subtask etl_mongo_to_clickhouse
[2024-12-18T09:55:30.955+0000] {task_command.py:467} INFO - Running <TaskInstance: etl_mongodb.etl_mongo_to_clickhouse scheduled__2024-12-18T01:00:00+00:00 [running]> on host ea437989725c
[2024-12-18T09:55:31.243+0000] {taskinstance.py:3132} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='Tohid' AIRFLOW_CTX_DAG_ID='etl_mongodb' AIRFLOW_CTX_TASK_ID='etl_mongo_to_clickhouse' AIRFLOW_CTX_EXECUTION_DATE='2024-12-18T01:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2024-12-18T01:00:00+00:00'
[2024-12-18T09:55:31.248+0000] {logging_mixin.py:190} INFO - Task instance is in running state
[2024-12-18T09:55:31.249+0000] {logging_mixin.py:190} INFO -  Previous state of the Task instance: queued
[2024-12-18T09:55:31.250+0000] {logging_mixin.py:190} INFO - Current task name:etl_mongo_to_clickhouse state:running start_date:2024-12-18 09:55:30.657471+00:00
[2024-12-18T09:55:31.250+0000] {logging_mixin.py:190} INFO - Dag name:etl_mongodb and current dag run status:running
[2024-12-18T09:55:31.251+0000] {taskinstance.py:731} INFO - ::endgroup::
[2024-12-18T09:55:31.374+0000] {logging_mixin.py:190} INFO - Number of documents in 'students' collection: 10000
[2024-12-18T09:55:31.521+0000] {taskinstance.py:3311} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 767, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 733, in _execute_callable
    return ExecutionCallableRunner(
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 422, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 238, in execute
    return_value = self.execute_callable()
                   ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 256, in execute_callable
    return runner.run(*self.op_args, **self.op_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/airflow/dags/process.py", line 53, in etl
    client_clickhouse.insert('airflow.students', student_data)  # Use the 'students' table in the 'airflow' database
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/clickhouse_connect/driver/client.py", line 628, in insert
    context.data = data
    ^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/clickhouse_connect/driver/insert.py", line 96, in data
    self.block_row_count = self._calc_block_size()
                           ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/clickhouse_connect/driver/insert.py", line 118, in _calc_block_size
    d_size = d_type.data_size(sample)
             ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/clickhouse_connect/datatypes/base.py", line 106, in data_size
    d_size = self._data_size(sample)
             ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/clickhouse_connect/datatypes/string.py", line 30, in _data_size
    total += len(x)
             ^^^^^^
TypeError: object of type 'int' has no len()
[2024-12-18T09:55:31.560+0000] {logging_mixin.py:190} INFO - Task instance in failure state
[2024-12-18T09:55:31.560+0000] {logging_mixin.py:190} INFO - Task start:2024-12-18 09:55:30.657471+00:00 end:2024-12-18 09:55:31.558307+00:00 duration:0.900836
[2024-12-18T09:55:31.561+0000] {logging_mixin.py:190} INFO - Task:<Task(PythonOperator): etl_mongo_to_clickhouse> dag:<DAG: etl_mongodb> dagrun:<DagRun etl_mongodb @ 2024-12-18 01:00:00+00:00: scheduled__2024-12-18T01:00:00+00:00, state:running, queued_at: 2024-12-18 09:55:23.274819+00:00. externally triggered: False>
[2024-12-18T09:55:31.564+0000] {logging_mixin.py:190} INFO - Failure caused by object of type 'int' has no len()
[2024-12-18T09:55:31.565+0000] {taskinstance.py:1225} INFO - Marking task as UP_FOR_RETRY. dag_id=etl_mongodb, task_id=etl_mongo_to_clickhouse, run_id=scheduled__2024-12-18T01:00:00+00:00, execution_date=20241218T010000, start_date=20241218T095530, end_date=20241218T095531
[2024-12-18T09:55:31.626+0000] {taskinstance.py:340} INFO - ::group::Post task execution logs
[2024-12-18T09:55:31.627+0000] {standard_task_runner.py:124} ERROR - Failed to execute job 47 for task etl_mongo_to_clickhouse (object of type 'int' has no len(); 110)
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/task/task_runner/standard_task_runner.py", line 117, in _start_by_fork
    ret = args.func(args, dag=self.dag)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/cli/cli_config.py", line 49, in command
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/cli.py", line 116, in wrapper
    return f(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/cli/commands/task_command.py", line 483, in task_run
    task_return_code = _run_task_by_selected_method(args, _dag, ti)
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/cli/commands/task_command.py", line 256, in _run_task_by_selected_method
    return _run_raw_task(args, ti)
           ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/cli/commands/task_command.py", line 341, in _run_raw_task
    return ti._run_raw_task(
           ^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/session.py", line 97, in wrapper
    return func(*args, session=session, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 3005, in _run_raw_task
    return _run_raw_task(
           ^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 273, in _run_raw_task
    TaskInstance._execute_task_with_callbacks(
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 3159, in _execute_task_with_callbacks
    result = self._execute_task(context, task_orig)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 3183, in _execute_task
    return _execute_task(self, context, task_orig)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 767, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 733, in _execute_callable
    return ExecutionCallableRunner(
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 422, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 238, in execute
    return_value = self.execute_callable()
                   ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 256, in execute_callable
    return runner.run(*self.op_args, **self.op_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/airflow/dags/process.py", line 53, in etl
    client_clickhouse.insert('airflow.students', student_data)  # Use the 'students' table in the 'airflow' database
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/clickhouse_connect/driver/client.py", line 628, in insert
    context.data = data
    ^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/clickhouse_connect/driver/insert.py", line 96, in data
    self.block_row_count = self._calc_block_size()
                           ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/clickhouse_connect/driver/insert.py", line 118, in _calc_block_size
    d_size = d_type.data_size(sample)
             ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/clickhouse_connect/datatypes/base.py", line 106, in data_size
    d_size = self._data_size(sample)
             ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/clickhouse_connect/datatypes/string.py", line 30, in _data_size
    total += len(x)
             ^^^^^^
TypeError: object of type 'int' has no len()
[2024-12-18T09:55:31.669+0000] {local_task_job_runner.py:266} INFO - Task exited with return code 1
[2024-12-18T09:55:31.750+0000] {taskinstance.py:3895} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-12-18T09:55:31.761+0000] {local_task_job_runner.py:245} INFO - ::endgroup::
[2024-12-18T10:16:12.787+0000] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2024-12-18T10:16:12.848+0000] {taskinstance.py:2613} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: etl_mongodb.etl_mongo_to_clickhouse scheduled__2024-12-18T01:00:00+00:00 [queued]>
[2024-12-18T10:16:12.862+0000] {taskinstance.py:2613} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: etl_mongodb.etl_mongo_to_clickhouse scheduled__2024-12-18T01:00:00+00:00 [queued]>
[2024-12-18T10:16:12.862+0000] {taskinstance.py:2866} INFO - Starting attempt 1 of 2
[2024-12-18T10:16:12.890+0000] {taskinstance.py:2889} INFO - Executing <Task(PythonOperator): etl_mongo_to_clickhouse> on 2024-12-18 01:00:00+00:00
[2024-12-18T10:16:12.910+0000] {warnings.py:112} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:70: DeprecationWarning: This process (pid=80) is multi-threaded, use of fork() may lead to deadlocks in the child.
  pid = os.fork()

[2024-12-18T10:16:12.913+0000] {standard_task_runner.py:72} INFO - Started process 121 to run task
[2024-12-18T10:16:12.922+0000] {standard_task_runner.py:104} INFO - Running: ['***', 'tasks', 'run', 'etl_mongodb', 'etl_mongo_to_clickhouse', 'scheduled__2024-12-18T01:00:00+00:00', '--job-id', '78', '--raw', '--subdir', 'DAGS_FOLDER/dag.py', '--cfg-path', '/tmp/tmpe58oloec']
[2024-12-18T10:16:12.924+0000] {standard_task_runner.py:105} INFO - Job 78: Subtask etl_mongo_to_clickhouse
[2024-12-18T10:16:13.258+0000] {task_command.py:467} INFO - Running <TaskInstance: etl_mongodb.etl_mongo_to_clickhouse scheduled__2024-12-18T01:00:00+00:00 [running]> on host ef884cc6896f
[2024-12-18T10:16:13.752+0000] {taskinstance.py:3132} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='Tohid' AIRFLOW_CTX_DAG_ID='etl_mongodb' AIRFLOW_CTX_TASK_ID='etl_mongo_to_clickhouse' AIRFLOW_CTX_EXECUTION_DATE='2024-12-18T01:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2024-12-18T01:00:00+00:00'
[2024-12-18T10:16:13.757+0000] {logging_mixin.py:190} INFO - Task instance is in running state
[2024-12-18T10:16:13.758+0000] {logging_mixin.py:190} INFO -  Previous state of the Task instance: queued
[2024-12-18T10:16:13.762+0000] {logging_mixin.py:190} INFO - Current task name:etl_mongo_to_clickhouse state:running start_date:2024-12-18 10:16:12.848617+00:00
[2024-12-18T10:16:13.762+0000] {logging_mixin.py:190} INFO - Dag name:etl_mongodb and current dag run status:running
[2024-12-18T10:16:13.763+0000] {taskinstance.py:731} INFO - ::endgroup::
[2024-12-18T10:16:13.913+0000] {logging_mixin.py:190} INFO - Number of documents in 'students' collection: 10000
[2024-12-18T10:16:14.020+0000] {logging_mixin.py:190} INFO - Inserted 10 records into ClickHouse.
[2024-12-18T10:16:14.021+0000] {python.py:240} INFO - Done. Returned value was: None
[2024-12-18T10:16:14.042+0000] {taskinstance.py:340} INFO - ::group::Post task execution logs
[2024-12-18T10:16:14.042+0000] {taskinstance.py:352} INFO - Marking task as SUCCESS. dag_id=etl_mongodb, task_id=etl_mongo_to_clickhouse, run_id=scheduled__2024-12-18T01:00:00+00:00, execution_date=20241218T010000, start_date=20241218T101612, end_date=20241218T101614
[2024-12-18T10:16:14.059+0000] {logging_mixin.py:190} INFO - Task instance in success state
[2024-12-18T10:16:14.059+0000] {logging_mixin.py:190} INFO -  Previous state of the Task instance: running
[2024-12-18T10:16:14.059+0000] {logging_mixin.py:190} INFO - Dag name:etl_mongodb queued_at:2024-12-18 10:16:05.470672+00:00
[2024-12-18T10:16:14.060+0000] {logging_mixin.py:190} INFO - Task hostname:ef884cc6896f operator:PythonOperator
[2024-12-18T10:16:14.112+0000] {local_task_job_runner.py:266} INFO - Task exited with return code 0
[2024-12-18T10:16:14.136+0000] {taskinstance.py:3895} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-12-18T10:16:14.137+0000] {local_task_job_runner.py:245} INFO - ::endgroup::
