[2024-12-18T09:55:30.330+0000] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2024-12-18T09:55:30.808+0000] {taskinstance.py:2613} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: etl_mongodb.etl_mongo_to_clickhouse scheduled__2024-12-18T04:00:00+00:00 [queued]>
[2024-12-18T09:55:30.850+0000] {taskinstance.py:2613} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: etl_mongodb.etl_mongo_to_clickhouse scheduled__2024-12-18T04:00:00+00:00 [queued]>
[2024-12-18T09:55:30.851+0000] {taskinstance.py:2866} INFO - Starting attempt 1 of 2
[2024-12-18T09:55:30.933+0000] {taskinstance.py:2889} INFO - Executing <Task(PythonOperator): etl_mongo_to_clickhouse> on 2024-12-18 04:00:00+00:00
[2024-12-18T09:55:30.960+0000] {warnings.py:112} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:70: DeprecationWarning: This process (pid=98) is multi-threaded, use of fork() may lead to deadlocks in the child.
  pid = os.fork()

[2024-12-18T09:55:30.962+0000] {standard_task_runner.py:72} INFO - Started process 118 to run task
[2024-12-18T09:55:30.965+0000] {standard_task_runner.py:104} INFO - Running: ['***', 'tasks', 'run', 'etl_mongodb', 'etl_mongo_to_clickhouse', 'scheduled__2024-12-18T04:00:00+00:00', '--job-id', '44', '--raw', '--subdir', 'DAGS_FOLDER/dag.py', '--cfg-path', '/tmp/tmpkyafgmcu']
[2024-12-18T09:55:30.970+0000] {standard_task_runner.py:105} INFO - Job 44: Subtask etl_mongo_to_clickhouse
[2024-12-18T09:55:31.104+0000] {task_command.py:467} INFO - Running <TaskInstance: etl_mongodb.etl_mongo_to_clickhouse scheduled__2024-12-18T04:00:00+00:00 [running]> on host ea437989725c
[2024-12-18T09:55:31.401+0000] {taskinstance.py:3132} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='Tohid' AIRFLOW_CTX_DAG_ID='etl_mongodb' AIRFLOW_CTX_TASK_ID='etl_mongo_to_clickhouse' AIRFLOW_CTX_EXECUTION_DATE='2024-12-18T04:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2024-12-18T04:00:00+00:00'
[2024-12-18T09:55:31.404+0000] {logging_mixin.py:190} INFO - Task instance is in running state
[2024-12-18T09:55:31.409+0000] {logging_mixin.py:190} INFO -  Previous state of the Task instance: queued
[2024-12-18T09:55:31.412+0000] {logging_mixin.py:190} INFO - Current task name:etl_mongo_to_clickhouse state:running start_date:2024-12-18 09:55:30.808704+00:00
[2024-12-18T09:55:31.414+0000] {logging_mixin.py:190} INFO - Dag name:etl_mongodb and current dag run status:running
[2024-12-18T09:55:31.415+0000] {taskinstance.py:731} INFO - ::endgroup::
[2024-12-18T09:55:31.528+0000] {logging_mixin.py:190} INFO - Number of documents in 'students' collection: 10000
[2024-12-18T09:55:31.626+0000] {taskinstance.py:3311} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 767, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 733, in _execute_callable
    return ExecutionCallableRunner(
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 422, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 238, in execute
    return_value = self.execute_callable()
                   ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 256, in execute_callable
    return runner.run(*self.op_args, **self.op_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/airflow/dags/process.py", line 53, in etl
    client_clickhouse.insert('airflow.students', student_data)  # Use the 'students' table in the 'airflow' database
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/clickhouse_connect/driver/client.py", line 628, in insert
    context.data = data
    ^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/clickhouse_connect/driver/insert.py", line 96, in data
    self.block_row_count = self._calc_block_size()
                           ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/clickhouse_connect/driver/insert.py", line 118, in _calc_block_size
    d_size = d_type.data_size(sample)
             ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/clickhouse_connect/datatypes/base.py", line 106, in data_size
    d_size = self._data_size(sample)
             ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/clickhouse_connect/datatypes/string.py", line 30, in _data_size
    total += len(x)
             ^^^^^^
TypeError: object of type 'int' has no len()
[2024-12-18T09:55:31.672+0000] {logging_mixin.py:190} INFO - Task instance in failure state
[2024-12-18T09:55:31.673+0000] {logging_mixin.py:190} INFO - Task start:2024-12-18 09:55:30.808704+00:00 end:2024-12-18 09:55:31.669051+00:00 duration:0.860347
[2024-12-18T09:55:31.673+0000] {logging_mixin.py:190} INFO - Task:<Task(PythonOperator): etl_mongo_to_clickhouse> dag:<DAG: etl_mongodb> dagrun:<DagRun etl_mongodb @ 2024-12-18 04:00:00+00:00: scheduled__2024-12-18T04:00:00+00:00, state:running, queued_at: 2024-12-18 09:55:23.861477+00:00. externally triggered: False>
[2024-12-18T09:55:31.674+0000] {logging_mixin.py:190} INFO - Failure caused by object of type 'int' has no len()
[2024-12-18T09:55:31.674+0000] {taskinstance.py:1225} INFO - Marking task as UP_FOR_RETRY. dag_id=etl_mongodb, task_id=etl_mongo_to_clickhouse, run_id=scheduled__2024-12-18T04:00:00+00:00, execution_date=20241218T040000, start_date=20241218T095530, end_date=20241218T095531
[2024-12-18T09:55:31.715+0000] {taskinstance.py:340} INFO - ::group::Post task execution logs
[2024-12-18T09:55:31.716+0000] {standard_task_runner.py:124} ERROR - Failed to execute job 44 for task etl_mongo_to_clickhouse (object of type 'int' has no len(); 118)
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/task/task_runner/standard_task_runner.py", line 117, in _start_by_fork
    ret = args.func(args, dag=self.dag)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/cli/cli_config.py", line 49, in command
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/cli.py", line 116, in wrapper
    return f(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/cli/commands/task_command.py", line 483, in task_run
    task_return_code = _run_task_by_selected_method(args, _dag, ti)
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/cli/commands/task_command.py", line 256, in _run_task_by_selected_method
    return _run_raw_task(args, ti)
           ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/cli/commands/task_command.py", line 341, in _run_raw_task
    return ti._run_raw_task(
           ^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/session.py", line 97, in wrapper
    return func(*args, session=session, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 3005, in _run_raw_task
    return _run_raw_task(
           ^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 273, in _run_raw_task
    TaskInstance._execute_task_with_callbacks(
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 3159, in _execute_task_with_callbacks
    result = self._execute_task(context, task_orig)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 3183, in _execute_task
    return _execute_task(self, context, task_orig)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 767, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 733, in _execute_callable
    return ExecutionCallableRunner(
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 422, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 238, in execute
    return_value = self.execute_callable()
                   ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 256, in execute_callable
    return runner.run(*self.op_args, **self.op_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/airflow/dags/process.py", line 53, in etl
    client_clickhouse.insert('airflow.students', student_data)  # Use the 'students' table in the 'airflow' database
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/clickhouse_connect/driver/client.py", line 628, in insert
    context.data = data
    ^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/clickhouse_connect/driver/insert.py", line 96, in data
    self.block_row_count = self._calc_block_size()
                           ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/clickhouse_connect/driver/insert.py", line 118, in _calc_block_size
    d_size = d_type.data_size(sample)
             ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/clickhouse_connect/datatypes/base.py", line 106, in data_size
    d_size = self._data_size(sample)
             ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/clickhouse_connect/datatypes/string.py", line 30, in _data_size
    total += len(x)
             ^^^^^^
TypeError: object of type 'int' has no len()
[2024-12-18T09:55:31.776+0000] {local_task_job_runner.py:266} INFO - Task exited with return code 1
[2024-12-18T09:55:31.805+0000] {local_task_job_runner.py:245} INFO - ::endgroup::
[2024-12-18T10:16:12.343+0000] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2024-12-18T10:16:12.430+0000] {taskinstance.py:2613} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: etl_mongodb.etl_mongo_to_clickhouse scheduled__2024-12-18T04:00:00+00:00 [queued]>
[2024-12-18T10:16:12.455+0000] {taskinstance.py:2613} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: etl_mongodb.etl_mongo_to_clickhouse scheduled__2024-12-18T04:00:00+00:00 [queued]>
[2024-12-18T10:16:12.455+0000] {taskinstance.py:2866} INFO - Starting attempt 1 of 2
[2024-12-18T10:16:12.507+0000] {taskinstance.py:2889} INFO - Executing <Task(PythonOperator): etl_mongo_to_clickhouse> on 2024-12-18 04:00:00+00:00
[2024-12-18T10:16:12.547+0000] {warnings.py:112} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:70: DeprecationWarning: This process (pid=86) is multi-threaded, use of fork() may lead to deadlocks in the child.
  pid = os.fork()

[2024-12-18T10:16:12.553+0000] {standard_task_runner.py:72} INFO - Started process 104 to run task
[2024-12-18T10:16:12.573+0000] {standard_task_runner.py:104} INFO - Running: ['***', 'tasks', 'run', 'etl_mongodb', 'etl_mongo_to_clickhouse', 'scheduled__2024-12-18T04:00:00+00:00', '--job-id', '71', '--raw', '--subdir', 'DAGS_FOLDER/dag.py', '--cfg-path', '/tmp/tmpxxi65k1k']
[2024-12-18T10:16:12.580+0000] {standard_task_runner.py:105} INFO - Job 71: Subtask etl_mongo_to_clickhouse
[2024-12-18T10:16:12.740+0000] {task_command.py:467} INFO - Running <TaskInstance: etl_mongodb.etl_mongo_to_clickhouse scheduled__2024-12-18T04:00:00+00:00 [running]> on host ef884cc6896f
[2024-12-18T10:16:13.601+0000] {taskinstance.py:3132} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='Tohid' AIRFLOW_CTX_DAG_ID='etl_mongodb' AIRFLOW_CTX_TASK_ID='etl_mongo_to_clickhouse' AIRFLOW_CTX_EXECUTION_DATE='2024-12-18T04:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2024-12-18T04:00:00+00:00'
[2024-12-18T10:16:13.605+0000] {logging_mixin.py:190} INFO - Task instance is in running state
[2024-12-18T10:16:13.608+0000] {logging_mixin.py:190} INFO -  Previous state of the Task instance: queued
[2024-12-18T10:16:13.610+0000] {logging_mixin.py:190} INFO - Current task name:etl_mongo_to_clickhouse state:running start_date:2024-12-18 10:16:12.431420+00:00
[2024-12-18T10:16:13.612+0000] {logging_mixin.py:190} INFO - Dag name:etl_mongodb and current dag run status:running
[2024-12-18T10:16:13.619+0000] {taskinstance.py:731} INFO - ::endgroup::
[2024-12-18T10:16:13.762+0000] {logging_mixin.py:190} INFO - Number of documents in 'students' collection: 10000
[2024-12-18T10:16:13.874+0000] {logging_mixin.py:190} INFO - Inserted 10 records into ClickHouse.
[2024-12-18T10:16:13.875+0000] {python.py:240} INFO - Done. Returned value was: None
[2024-12-18T10:16:13.904+0000] {taskinstance.py:340} INFO - ::group::Post task execution logs
[2024-12-18T10:16:13.909+0000] {taskinstance.py:352} INFO - Marking task as SUCCESS. dag_id=etl_mongodb, task_id=etl_mongo_to_clickhouse, run_id=scheduled__2024-12-18T04:00:00+00:00, execution_date=20241218T040000, start_date=20241218T101612, end_date=20241218T101613
[2024-12-18T10:16:13.943+0000] {logging_mixin.py:190} INFO - Task instance in success state
[2024-12-18T10:16:13.943+0000] {logging_mixin.py:190} INFO -  Previous state of the Task instance: running
[2024-12-18T10:16:13.944+0000] {logging_mixin.py:190} INFO - Dag name:etl_mongodb queued_at:2024-12-18 10:16:05.838330+00:00
[2024-12-18T10:16:13.948+0000] {logging_mixin.py:190} INFO - Task hostname:ef884cc6896f operator:PythonOperator
[2024-12-18T10:16:14.032+0000] {local_task_job_runner.py:266} INFO - Task exited with return code 0
[2024-12-18T10:16:14.064+0000] {taskinstance.py:3895} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-12-18T10:16:14.066+0000] {local_task_job_runner.py:245} INFO - ::endgroup::
